version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: neighborswap-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: neighborswap
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - neighborswap-dev-network

  # Backend API (Development)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: neighborswap-backend-dev
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      NODE_ENV: development
      PORT: 5001
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/neighborswap?authSource=admin
      JWT_SECRET: neighborswap_dev_secret_key_2024
      JWT_EXPIRE: 7d
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads
    networks:
      - neighborswap-dev-network

  # Frontend React App (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: neighborswap-frontend-dev
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:5001/api
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - neighborswap-dev-network

volumes:
  mongodb_dev_data:
    driver: local

networks:
  neighborswap-dev-network:
    driver: bridge